name: Cypress Tests

on: push

jobs:
  cypress-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:e2e:run:all
        continue-on-error: true # Continue even if tests fail

      - name: Generate MochaAwesome report
        run: npx marge ./cypress/reports --reportDir ./cypress/reports --cdn
        if: always() # Always execute this step

      - name: Upload MochaAwesome report
        uses: actions/upload-artifact@v2
        with:
          name: my-single-file-artifact
          path: cypress/reports/todo.html

      - name: 'Publish test results'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.CYPRESS }}
          publish_dir: './cypress/reports'
          keep_files: true
